name: country_list
description: A new Flutter project with clean architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # list and collections utils
  collection: ^1.17.0

  # state management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.0

  # di
  get_it: ^7.3.0

  # retrofit
  retrofit: '>=4.0.0 <5.0.0'
  awesome_dio_interceptor: ^1.0.0

  # SVG support
  flutter_svg: ^2.0.5

  # loading placeholder
  skeletons: ^0.0.3

  # grid view
  flutter_staggered_grid_view: ^0.6.2

  # multi language
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/json/users.json
    - assets/language/