name: country_list
description: A new Flutter project with clean architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # list and collections utils
  collection: ^1.17.0

  # state management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.0

  # di
  get_it: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/users.json